displayName=Surge Timer
author=javlanoob
support=https://github.com/javlanoob/surge-timer
description=Puts a timer over the surge potion
tags=surge,potion,special,attack,spec,cooldown,timer,adrenaline
plugins=com.surgetimer.SurgeTimerPlugin
build=standard
